/services:
  post:
    tags:
      - services
    summary: Создать услугу
    description: Создает новую услугу
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              price:
                type: number
              images:
                type: array
                items:
                  type: string
              regionId:
                type: string
              cityId:
                type: string
              categoryId:
                type: string
              subcategoryId:
                type: string
            required:
              - title
              - description
              - price
              - regionId
              - cityId
              - categoryId
              - subcategoryId
    responses:
      '201':
        description: Услуга создана
      '400':
        description: Ошибка данных
      '500':
        description: Ошибка сервера

  get:
    tags:
      - services
    summary: Получить список услуг
    description: Получает список услуг с возможностью фильтрации по региону, городу, категории, подкатегории, поиску и цене
    parameters:
      - name: regionId
        in: query
        schema:
          type: string
      - name: cityId
        in: query
        schema:
          type: string
      - name: categoryId
        in: query
        schema:
          type: string
      - name: subcategoryId
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: price
        in: query
        schema:
          type: number
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: limit
        in: query
        schema:
          type: integer
          default: 20
    responses:
      '200':
        description: Список услуг получен
      '500':
        description: Ошибка сервера

/services/{id}/promote:
  post:
    tags:
      - services
    summary: Поднять услугу в топ
    description: Платное продвижение услуги на 3 или 7 дней
    security:
      - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              days:
                type: integer
            required:
              - days
    responses:
      '200':
        description: Услуга продвинута
      '400':
        description: Ошибка данных
      '500':
        description: Ошибка сервера

/services/{id}/contact:
  post:
    tags:
      - services
    summary: Купить контакт провайдера
    description: Открывает контактную информацию провайдера за монеты
    security:
      - BearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Контакт получен
      '400':
        description: Ошибка
      '500':
        description: Ошибка сервера
